apiVersion: v1
kind: Deployment
metadata:
  name: grafana
spec:
  containers:
    - name : grafana
      image: grafana
      ports: 
      - containerPort: 3000
      # imagePullPolicy: Never
    - name : influxdb
      image: influxdb
      # imagePullPolicy: Never