apiVersion: apps/v1
kind: Deployment
metadata:
  name: dep-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: cont-nginx
        image: im-nginx
        imagePullPolicy: Never
        ports:
          - containerPort: 80
          - containerPort: 443
          - containerPort: 22
---
apiVersion: v1
kind: Service
metadata:
  name: svc-nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.101
  ports:
    - port: 80
      name: http
      protocol: TCP
      targetPort: 80
    - port: 443
      name: https
      protocol: TCP
      targetPort: 443
    - port: 22
      name: ssh
      protocol: TCP
      targetPort: 22
  selector:
    app: nginx