apiVersion: apps/v1
kind: Deployment
metadata:
  name: phpmyadmin
  labels:
    app: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
        - name: cont-phpmyadmin
          image: im-phpmyadmin
          imagePullPolicy: Never
          ports:
            - containerPort: 5000
          # env:
          #   - name: PMA_HOST
          #     value: "serv-mysql"
          #   - name: PMA_PORT
          #     value: "3306"
          #   - name: MYSQL_ROOT_PASSWORD
          #     valueFrom:
          #       secretKeyRef:
          #         name: secret-mysql
          #         key: root-password
---
apiVersion: v1
kind: Service
metadata:
  name: serv-phpmyadmin
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.102
  ports:
    - port: 5000
      targetPort: 5000
      name: http
      protocol: TCP
  selector:
    app: phpmyadmin