apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
        - name : wordpress
          image: wordpress 
          ports:
          - containerPort: 5050
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: serv-wordpress
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.99.104
  ports:
    - port: 5050
      targetPort: 5050
      name: http
      protocol: TCP
  selector:
    app: wordpress